
services:
###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80"
###< symfony/mercure-bundle ###

###> meilisearch/search-bundle ###
  meilisearch:
    ports:
      - "7700"
###< meilisearch/search-bundle ###
